### ISSUE TITLE
BytedeskUserHttpApi().registerUser 方法里，没有处理 responseJson['data'] == false 的情形

### ISSUE THREAD

**Issue by JimmyLee05** [Bytedesk/bytedesk-flutter#1]
首次登录客服系统，再删除应用后，本地保存的数据会清空。

这时去请求注册一个用户，会出现用户已注册，responseJson['data'] == false 的情形。

**Comment by pengjinning** [comment]
技术支持QQ3群: 825257535
技术支持QQ: 2939499399
